# Generated by Django 2.1 on 2018-08-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('goods_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('goods_number', models.IntegerField()),
                ('goods_price', models.FloatField()),
            ],
        ),
    ]
